[tool.semantic_release]
branch = "main"
version_variable = [
        "workflow/scripts/__init__.py:__version__"
]
changelog_file = "CHANGELOG.md"
upload_to_pypi = false
upload_to_release = false

[tool.isort]
profile = "black"
skip_gitignore = true
float_to_top = false

[tool.flake8]
select = "ANN,B,B901,B902,B903,C,C4,D,DAR,F,S,SC"
ignore = "ANN101,S101"
exclude = [".tests/*"]
max-line-length = 88
max-complexity = 10
docstring-convention = "numpy"
docstring-style = "numpy"
strictness = "short"
dictionaries = "en_US,python,technical"
spellcheck-targets = "comments"
