name: CI/CD
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  py_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: black_isort_flake8_mypy
        run: nox -s form lint type
      - name: safety
        run: nox -s security
  snake_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
          update-conda: true
          conda-channels: conda-forge, bioconda
      - name: Install Dependencies
        run: |
          conda install -c conda-forge mamba
          mamba install -c conda-forge -c bioconda --file workflow/envs/cicd_min.txt
      - name: Snakefmt_lint
        run: |
          snakemake --lint
          snakefmt workflow
      - name: Snakemake unit tests
        run: pytest .tests/unit
      - name: Snakemake integration tests
        run: pytest .tests/integration

  release:
    runs-on: ubuntu-latest
    needs: [py_check, snake_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
